### ISSUE TITLE
selecting nz doesn't seem to work

### ISSUE THREAD

**Issue by Xboarder56** [FingerlessGlov3s/OPNsensePIAWireguard#41]
Hi all,

I used to always utilize NZ but when running debug on it I get the following error:

This works fine using ca_vancouver for now but ideally wanted NZ for game releases. 

```}

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x84d9ad4f0>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='newzealand403', port=1337): Max retries exceeded with url: /addKey?pt=X3mn_nI%3D&pubkey=RFQGApP3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x84d9ad4f0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/conf/PIAWireguard.py", line 607, in <module>
    wireguardResponse = requests.get(f"https://{piaWgCn}:1337/addKey", params=createObject, verify=piaCA)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='newzealand403', port=1337): Max retries exceeded with url: /addKey?pt=3mn_nI%3D&pubkey=0zQ%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x84d9ad4f0>: Failed to establish a new connection: [Errno 60] Operation timed out'))```

**Comment by FingerlessGlov3s** [comment]
I can reach https://179.61.240.28:1337, are you able to reach this yourself in a browser? Your logs show that you can't for whatever reason. Unless it was down and now it's back up. I don't believe this to be a fault with the script and it will most likily be on PIA's end.

```json
{"ip":"179.61.240.28","cn":"newzealand403"}
```

The script pulls a server from PIA's serverlist, for the selected region and uses it, the logic doesn't change per region.

https://serverlist.piaservers.net/vpninfo/servers/v6

**Comment by Xboarder56** [comment]
weird some reason that gets allowed out and just never returns traffic back.

**Comment by Xboarder56** [comment]
Weird I had a coworker on the same isp in the city get the same issue. Must be the ISP doing something. Over a VPN on my phone (PIA) it will load that address fine.

**Comment by FingerlessGlov3s** [comment]
Could be a peering issue, do a trace route see what happens 🤔.

**Comment by Xboarder56** [comment]
I think your exactly right. Not even sure how I would get the ISP to fix that. (Thanks for checking anyways and confirming it's them)
![image](https://github.com/FingerlessGlov3s/OPNsensePIAWireguard/assets/967563/906e3238-0821-46a3-9599-4b0852bbaaaf)

**Comment by FingerlessGlov3s** [comment]
Not sure what ping you should be getting to NZ but since I see cox.net guessing higher than 32ms which I'm seeing highest ping you can reach.
I assumed it would be more 100ms+ by the time you get to NZ.

Defo issue with ISP or a peering of theirs.
