### ISSUE TITLE
Cannot list servers, PIA might have dropped the API

### ISSUE THREAD

**Issue by dacabdi** [FingerlessGlov3s/OPNsensePIAWireguard#66]
The script cannot reach out to list the servers. I tried the same URL with curl on the side and it is returning 404. PIA might have dropped the API.

```
DEBUG:JSON validation successful.
DEBUG:Getting OPNsense WireGuard Instances
DEBUG:Starting new HTTPS connection (1): 127.0.0.1:443
DEBUG:https://127.0.0.1:443 "GET /api/wireguard/server/searchServer/ HTTP/1.1" 200 296
DEBUG:Creating/Populating Wireguard Instances array
DEBUG:Setting up python script for instance default
DEBUG:Looking for server instance pia-default in gathered opnsense instances
DEBUG:Getting WireGuard instance for default
DEBUG:https://127.0.0.1:443 "GET /api/wireguard/server/getServer/164d9da2-446d-46ff-8efd-3132db73a008 HTTP/1.1" 200 505
DEBUG:Getting peer details (PIA's Server)
DEBUG:https://127.0.0.1:443 "GET /api/wireguard/client/getClient/e30e6563-3979-45a7-b1d7-b89f77aca51f HTTP/1.1" 200 345
DEBUG:Finished getting default tunnel instance information from OPNsense
DEBUG:Checking handshakes
DEBUG:https://127.0.0.1:443 "GET /api/wireguard/service/show/ HTTP/1.1" 200 557
DEBUG:default tunnel down - last handshake 932238 seconds ago
DEBUG:Starting new HTTPS connection (1): serverlist.piaservers.net:443
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x848f8bee0>: Failed to establish a new connection: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='serverlist.piaservers.net', port=443): Max retries exceeded with url: /vpninfo/servers/v6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x848f8bee0>: Failed to establish a new connection: [Errno 65] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/conf/PIAWireguard.py", line 463, in <module>
    serverList = PIAServerList()
  File "/conf/PIAWireguard.py", line 142, in PIAServerList
    r = requests.get(url, headers={'User-Agent': 'Github: FingerlessGlov3s/OPNsensePIAWireguard'}, timeout=10)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='serverlist.piaservers.net', port=443): Max retries exceeded with url: /vpninfo/servers/v6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x848f8bee0>: Failed to establish a new connection: [Errno 65] No route to host'))
```

**Comment by dacabdi** [comment]
Nevermind, weird network issue on my side.
